### ISSUE TITLE
Prefer base64 over binascii

### ISSUE THREAD

**Issue by berndverst** [jimbobbennett/AttendeeDetectorWorkshop#1]
`binascii` is intended to be low-level. Use `base64` library, `base64.encode`

For example here:
https://github.com/jimbobbennett/AttendeeDetectorWorkshop/blob/master/Steps/AddWebApi.md

Docs:
https://docs.python.org/3/library/base64.html

**Comment by jimbobbennett** [comment]
Changed to use Base64. Thanks @berndverst!
